name: Android Build and Deployment Pipeline

on:
  push:
    branches:
      - 'release_*'
      - 'master'
  workflow_dispatch:
    inputs:
      app_id:
        description: 'The application Id of the current build'
        required: true
      branch:
        description: 'The branch from which we have to build'
        required: true

jobs:
  build:
    name: Setup Environment and build
    runs-on: self-hosted
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

